# site description
# 网站描述
description = "Hugo DoIt 主题官方文档"
# site keywords
# 网站关键词
keywords = ["Theme", "Hugo"]
# App icon config
# 应用图标配置
[app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
  title = "mywebsite"
  # whether to omit favicon resource links
  # 是否隐藏网站图标资源链接
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
  svgFavicon = ""
  # Safari mask icon color
  # Safari 图标颜色
  iconColor = "#5bbad5"
  # Windows v8-10 tile color
  # Windows v8-10 磁贴颜色
  tileColor = "#da532c"
# Search config
# 搜索配置
[search]
  enable = true
  # type of search engine ("algolia", "fuse", "pagefind")
  # 搜索引擎的类型 ("algolia", "fuse", "pagefind")
  type = "algolia"
  # max index length of the chunked content
  # 文章内容最长索引长度
  contentLength = 4000
  # placeholder of the search bar
  # 搜索框的占位提示语
  placeholder = ""
  # max number of results length
  # 最大结果数目
  maxResultLength = 10
  # snippet length of the result
  # 结果内容片段长度
  snippetLength = 50
  # HTML tag name of the highlight part in results
  # 搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  # whether to use the absolute URL based on the baseURL in search index
  # 是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
  [search.algolia]
    index = "zh_cn_index"
    appID = "5YGRNRQK1G"
    searchKey = "0ff6874805de24b84aa1d5ebccad56cd"
  [search.fuse]
    # https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.1
    distance = 100
    ignoreLocation = true
    useExtendedSearch = false
    ignoreFieldNorm = false
  [search.pagefind]
    # https://pagefind.app/docs/search-config/#available-options
    # run `npx pagefind --site $YOUR_PUBLIC_DIR` after site build to create pagefind index
    termFrequency = 1.0
    pageLength = 0.75
    termSimilarity = 1.0
    termSaturation = 1.4
# Home page config
# 主页信息设置
[home]
  # amount of RSS pages
  # RSS 文章数目
  rss = 10
  # Home page profile
  # 主页个人信息
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    # Gravatar 邮箱，用于优先在主页显示的头像
    gravatarEmail = ""
    # URL of avatar shown in home page
    # 主页显示头像的 URL
    avatarURL = "/images/avatar.webp"
    # URL the avatar links to
    # 头像的链接指向的 URL
    avatarLinkURL = ""
    # title shown in home page (HTML format is supported)
    # 主页显示的网站标题 (支持 HTML 格式)
    title = "mywebsite"
    # subtitle shown in home page
    # 主页显示的网站副标题
    subtitle = "A blog about learning and life"
    # whether to use typeit animation for subtitle
    # 是否为副标题显示打字机动画
    typeit = true
    # whether to show social links
    # 是否显示社交账号
    social = true
    # disclaimer (HTML format is supported)
    # 免责声明 (支持 HTML 格式)
    disclaimer = ""
  # Home page posts
  # 主页文章列表
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    # 主页每页显示文章数量
    paginate = 3
# Social config in home page
# 主页的社交信息设置
[social]
  Angellist = ""           # 天使投资
  Bandcamp = ""            # Bandcamp 音乐平台
  Behance = ""             # Behance 作品展示
  Bilibili = ""            # 哔哩哔哩
  Bitbucket = ""           # Bitbucket 代码托管
  BuyMeACoffee = ""        # BuyMeACoffee 赞赏
  Codepen = ""             # Codepen 前端代码演示
  Deviantart = ""          # Deviantart 设计作品
  Devto = ""               # Dev.to 技术社区
  Douban = ""              # 豆瓣
  Dribbble = ""            # Dribbble 设计作品
  Email = "xxxx@xxxx.com"  # 邮箱
  Facebook = ""            # Facebook 脸书
  Fivehundredpx = ""       # 500px 摄影
  Flickr = ""              # Flickr 摄影
  Foursquare = ""          # Foursquare 地理位置
  FreeCodeCamp = ""        # FreeCodeCamp 编程学习
  Gitea = ""               # Gitea 代码托管
  GitHub = "steven-yl"     # GitHub 代码托管
  Gitlab = ""              # GitLab 代码托管
  Goodreads = ""           # Goodreads 读书
  Googlescholar = ""       # 谷歌学术
  Hackernews = ""          # Hacker News 技术资讯
  Instagram = ""           # Instagram 照片分享
  Jsfiddle = ""            # JSFiddle 前端代码演示
  Keybase = ""             # Keybase 加密通信
  Kickstarter = ""         # Kickstarter 众筹平台
  Ko-Fi = ""               # Ko-Fi 赞赏
  Lastfm = ""              # Last.fm 音乐
  Liberapay = ""           # Liberapay 捐赠
  Linkedin = ""            # 领英
  Linktree = ""            # Linktree 多链接页面
  Mastodon = ""            # Mastodon 去中心化社交
  Matrix = ""              # Matrix 去中心化通讯
  Medium = ""              # Medium 写作平台
  Mix = ""                 # Mix 社交书签
  Odnoklassniki = ""       # Odnoklassniki 俄语社交
  ORCID = ""               # ORCID 学者标识
  Patreon = ""             # Patreon 众筹资助
  Paypal = ""              # Paypal 支付
  Pinterest = ""           # Pinterest 图片收集
  QQ = ""                  # QQ
  QQGroup = ""             # QQ 群
  Quora = ""               # Quora 问答
  Reddit = ""              # Reddit 论坛
  Researchgate = ""        # ResearchGate 学术平台
  RSS = true               # RSS 订阅
  Skype = ""               # Skype 通讯
  Slidershare = ""         # Slideshare 幻灯片
  Snapchat = ""            # Snapchat 短视频
  Soundcloud = ""          # SoundCloud 音乐分享
  Spotify = ""             # Spotify 音乐
  Stackoverflow = ""       # Stack Overflow 编程问答
  Steam = ""               # Steam 游戏
  Strava = ""              # Strava 运动
  Telegram = ""            # Telegram 电报
  Thingiverse = ""         # Thingiverse 3D作品
  Tumblr = ""              # Tumblr 轻博客
  Twitch = ""              # Twitch 游戏直播
  Twitter = ""             # 推特
  Vine = ""                # Vine 视频
  VK = ""                  # VK 俄语社交
  Weibo = ""               # 微博
  Whatsapp = ""            # WhatsApp 通讯
  Wordpress = ""           # Wordpress 博客
  Xing = ""                # Xing 商务社交
  XMPP = ""                # XMPP 即时通讯
  Youtubechannel = ""      # YouTube频道
  Youtubecustom = ""       # YouTube自定义
  Youtubelegacy = ""       # YouTube旧版
  Zhihu = ""               # 知乎
  Bluesky = ""             # Bluesky 新社交
  # [social.Diaspora]        # Diaspora 去中心化社交
  #   id = "@xxxx"           # Diaspora 用户名
  #   prefix = "https://yyyy/"# Diaspora 前缀
# Sponsor config
# 赞助设置
[sponsor]
  enable = true
  bio = "如果你觉得这篇文章对你有所帮助，欢迎赞赏~"
  link = "https://github.com/sponsors/HEIGE-PCloud"
  # custom = "<a href=\"https://www.buymeacoffee.com/PCloud\" target=\"_blank\"><img src=\"https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png\" alt=\"Buy Me A Coffee\" style=\"height: 40px !important;width: 145 !important;\" ></a>"
